[**Lab #9 Markdown File**](/assignments/lab_9_hypotheses.Rmd)

In Lab #4, we asked you to identify several possible datasets you could use for a final project. In lab #5, we asked you to write two specific research questions about a dataset. For this lab, we want you to gain experience developing hypotheses using social science research. Please write two paragraphs below. Each paragraph should describe the hypothesis you want to test, including references to previous work that provide support for that hypothesis. For example, the theory of the “Strength of weak ties” might be used to support a hypothesis about the viral diffusion of YouTube videos (for a final project that was trying to determine why YouTube videos go viral).

You do not need to use the same research question and/or data you described in Lab #4 or #5. It is very common for students to change their research questions, datasets, and hypotheses throughout the semester. On the other hand, if you are happy with the research question and dataset you identified in previous labs, that’s great! Feel free to use it for this lab as well.

HINT: Learning to write hypotheses well is one of the hardest parts of doing social science research. A good hypothesis usually a) draws/builds upon previous research; and b) specifies the relationship between one variable and another (e.g. YouTube videos will spread further if the people who share them are connected by weak ties). Note that you may need to do some research to “develop” or “support” your hypotheses in this way. Google scholar is one of the best resources for this. Please support your hypotheses with peer reviewed evidence created by other researchers, instead of simple web links or non-peer reviewed content from Wikipedia.

------------------------------------------------------------------------

**Hypothesis #1:** School districts that are targeted by book bans are not in areas with large networks of resourced public libraries. The two variables being compared in this hypothesis are ratio of book bans and the quality of public library services. Book bans ultimately require a significant amount of funding to process (Langrock, 2023). On top of this, states such as Missouri, Michigan, Texas, Arkansas, and Wyoming among others, typically with larger Republican voter populations, have begun to defund libraries. As stated in "Book Bans in Political Context: Evidence from U.S. Public Schools," books are typically banned in libraries located in counties where there was a change vote share won by Republican candidates in U.S. presidential elections. Considering that book banning is a political strategy under this current context, there is potential indication that book bans are in areas with underresourced public libraries or currently deteriorating libraries.

**Hypothesis #2:** Demand for public libraries increase in areas that are targeted by book bans. The two variables being compared in this hypothesis are ratio of book bans and demand for public library services. In "Book Bans in Political Context: Evidence from U.S. Public Schools," the authors found that book banning is an ineffective censorship tactic and in some cases, may raise more awareness around these books. In "Book Bans in American Libraries: Impact of Politics on Inclusive Content Consumption," researchers found that circulations of banned books actually increased by 12%. However, there is little research on whether communities that have been targeted by book bans seek resources from their local libraries, and if book bans impact demand. Based on the research that has found an increase in attention surrounding banned books it could support potential increase in library usage in areas affected by book bans.

### Sources:

Ananthakrishnan, Uttara M and Basavaraj, Naveen and Karmegam, Sabari Rajan and Sen, Ananya and Smith, Michael D., Book Bans in American Libraries: Impact of Politics on Inclusive Content Consumption (June 23, 2023). Donald G. Costello College of Business at George Mason University Research Paper, Available at SSRN: <https://ssrn.com/abstract=4489684> or [http://dx.doi.org/10.2139/ssrn.4489684](https://dx.doi.org/10.2139/ssrn.4489684)

Langrock, Isabelle and LaViolette, Jack and Goncalves, Marcelo and Spoon, Katie, Book Bans in Political Context: Evidence from U.S. Public Schools (October 31, 2023). Available at SSRN: <https://ssrn.com/abstract=4618699> or [http://dx.doi.org/10.2139/ssrn.4618699](https://dx.doi.org/10.2139/ssrn.4618699)
